const Config = {
  brushes: [
    {
      value: "w",
      name: "Wall",
      shortName: "W",
      color: "black",
    },
    {
      value: "h",
      name: "Home",
      shortName: "H",
      color: "#C0392B",
    },
    {
      value: "f",
      name: "Food",
      shortName: "F",
      color: "#186A3B",
      decayable: true,
    },
    {
      value: "n",
      name: "NoFood",
      shortName: "N",
      color: "#0000FF",
      decayable: true,
      drawable: false,
    },
    {
      value: "d",
      name: "Dirt",
      shortName: "D",
      color: "#40260F",
      decayable: true,
    },
    {
      value: " ",
      shortName: "E",
      name: "Eraser",
    },
  ],
  MapBounds: [200, 112],
  PercentFoodReturnedToStopTime: 0.99,
  BlockDecaySteps: 10,
  FoodPerCell: 20,
  DirtPerCell: 50,
  NoFoodPerCell: 100,
  ViewAngle: 45,
  AntStepDistance: 0.3,
  AntWanderChance: 0.2,
  AntWanderAmount: 30,
  MaxSmellTurnRate: 55,
  MinSmellTurnRate: 20,
  ViewDistance: 2,
  TrailDropRate: 5,
  AntsToSpawn: 1000,
  StayOnCourseWanderAmount: 25,
  TrailDecayRange: 250,
  TrailTransparencyFloor: 0.005,
  TrailDecayInterval: 20,
};
module.exports = { Config };
